# Organisational Reputation and ML

## Constants and preparations

### Constants

In [1]:
import os

LABELS_JSON_FILENAME = "labels2.json"
# DOCUMENTS_DOCX_FOLDER = 'Training Set for Hugo'
DOCUMENTS_DOCX_FOLDER = '/home/hugo/MEGA/work/Agency_Classification/Teaching_sample_2019_34_agencies/Teaching sample 2019 34 agencies'
TEXTFILES_FOLDER = os.path.join(os.getcwd(), 'documents_txt')
RAW_DATA_JSON_FILE = 'raw_data.json'
PREPROCESSED_JSON_FILE = 'raw_data.json'

### Preparations

In [2]:
if not os.path.exists(TEXTFILES_FOLDER):
    os.makedirs(TEXTFILES_FOLDER)

## Read the labels

In [3]:
!ls

 agency_counts.csv			 label_agency_heatmap.png
 agency_label_crosstab.csv		 label_counts.csv
 agency_label_crosstab_percentages.csv	 labels2.json
 all_data.json				 labels.csv
 all_data_no_predictions.csv		 labels.json
 analyze.ipynb				 Machine_Learning.ipynb
'Coding for Hugo.xlsx'			 make_new_labels_file.ipynb
 confidence_pivot.csv			 pycaret.ipynb
 confidence_pivot_only_agencies.csv	 raw_data.json
 confidence_pivot_only_labels.csv	 regulatory_vs_non_regulatory.csv
 data_with_labels.csv			 regulatory_vs_non_regulatory.png
 documents_txt				 results
 dpc2vec.ipynb				 SVM_trained.pk
 evaluation_pivot.csv			'Training Set for Hugo'
 evaluation_pivot_only_agencies.csv	 vectorizer.pk
 evaluation_pivot_only_labels.csv	 year_label_heatmap.png
 experiments_results


In [4]:
from csv import DictReader

def read_labels(filename:str = "labels.csv"):
    data = []

    with open(filename, 'rt') as f:
        reader = DictReader(f, delimiter='\t')
        for line in reader:
            line['Dimension 1st'] = line['Dimension 1']
            line['Dimension 2nd'] = line['Dimension 2']
            
            del line['Dimension 1']
            del line['Dimension 2']
            
            data.append(line)
            
    print(f"{len(data)} lines loaded")
    return data
            
def process_labels(labels):
    for line in labels:
        if not line['Document'].endswith(".docx"):
            line["Document"] = line["Document"].strip() + ".docx"
        
        line['Dimension 1st'] = str(int(line['Dimension 1st']))
        line['Dimension 2nd'] = str(int(line['Dimension 2nd']))
    

In [5]:
label_names = {
    "1": "Technical",
    "2": "Performative",
    "3": "Procedural",
    "4": "Moral"
}

In [6]:
import os

labels_file = "labels_FINAL.csv"
labels_folder = "/home/hugo/MEGA/work/Agency_Classification"
labels_file_path = os.path.join(labels_folder, labels_file)
assert os.path.exists(labels_file_path)

In [7]:
import json

labels = read_labels(labels_file_path)
labels

1302 lines loaded


[OrderedDict([('Document', 'ACER 2019 1.docx'),
              ('Dimension 1st', '1'),
              ('Dimension 2nd', '1')]),
 OrderedDict([('Document', 'ACER 2019 2.docx'),
              ('Dimension 1st', '1'),
              ('Dimension 2nd', '2')]),
 OrderedDict([('Document', 'ACER 2019 3.docx'),
              ('Dimension 1st', '2'),
              ('Dimension 2nd', '3')]),
 OrderedDict([('Document', 'ACER 2019 4.docx'),
              ('Dimension 1st', '1'),
              ('Dimension 2nd', '1')]),
 OrderedDict([('Document', 'ACER 2019 5.docx'),
              ('Dimension 1st', '3'),
              ('Dimension 2nd', '3')]),
 OrderedDict([('Document', 'ACER 2019 6.docx'),
              ('Dimension 1st', '3'),
              ('Dimension 2nd', '3')]),
 OrderedDict([('Document', 'ACER 2019 7.docx'),
              ('Dimension 1st', '2'),
              ('Dimension 2nd', '1')]),
 OrderedDict([('Document', 'ACER 2019 8.docx'),
              ('Dimension 1st', '2'),
              ('Dimension 2nd', 

In [8]:
import json

labels = read_labels(labels_file_path)

process_labels(labels)
with open(LABELS_JSON_FILENAME, 'wt') as out:
    json.dump(labels, out)

    assert os.path.exists(LABELS_JSON_FILENAME), "The file must be created."
!ls

1302 lines loaded
 agency_counts.csv			 label_agency_heatmap.png
 agency_label_crosstab.csv		 label_counts.csv
 agency_label_crosstab_percentages.csv	 labels2.json
 all_data.json				 labels.csv
 all_data_no_predictions.csv		 labels.json
 analyze.ipynb				 Machine_Learning.ipynb
'Coding for Hugo.xlsx'			 make_new_labels_file.ipynb
 confidence_pivot.csv			 pycaret.ipynb
 confidence_pivot_only_agencies.csv	 raw_data.json
 confidence_pivot_only_labels.csv	 regulatory_vs_non_regulatory.csv
 data_with_labels.csv			 regulatory_vs_non_regulatory.png
 documents_txt				 results
 dpc2vec.ipynb				 SVM_trained.pk
 evaluation_pivot.csv			'Training Set for Hugo'
 evaluation_pivot_only_agencies.csv	 vectorizer.pk
 evaluation_pivot_only_labels.csv	 year_label_heatmap.png
 experiments_results


In [9]:
import json

with open(LABELS_JSON_FILENAME, 'rt') as f:
    labels = json.load(f)
    
print(len(labels))
print(labels[:5])

1302
[{'Document': 'ACER 2019 1.docx', 'Dimension 1st': '1', 'Dimension 2nd': '1'}, {'Document': 'ACER 2019 2.docx', 'Dimension 1st': '1', 'Dimension 2nd': '2'}, {'Document': 'ACER 2019 3.docx', 'Dimension 1st': '2', 'Dimension 2nd': '3'}, {'Document': 'ACER 2019 4.docx', 'Dimension 1st': '1', 'Dimension 2nd': '1'}, {'Document': 'ACER 2019 5.docx', 'Dimension 1st': '3', 'Dimension 2nd': '3'}]


In [18]:
for item in labels:
    if 'SBR' in item['Document']:
        print(item)

{'Document': 'SBR 2019 1.docx', 'Dimension 1st': '3', 'Dimension 2nd': '3', 'id': 'SBR 2019 1', 'text': 'Single Resolution Board extends prior permissions procedure\xa0\nThe Single Resolution Board’s procedure to assess applications to reduce eligible liabilities instruments under Article 78a of the Capital Requirements Regulation will remain in place until the relevant European Banking Authority’s Regulatory Technical Standards come into force.\xa0To continue performing market-making and other secondary market activities as of 1 January 2020, banks must obtain a prior permission.\xa0\nTo cover the period until the standards come into force, the SRB confirms and extends the\xa0\xa0in the CRR addendum to the SRB’s MREL policy:\nthe aggregate trading volume in these activities does not exceed 1% TREA on a consolidated basis at the level of the resolution group;\nany MREL shortfall, or increase thereof, resulting from these market-making activities is compensated with eligible liabilities

## Convert texts to txt

In [19]:
import docx
from tqdm import tqdm_notebook

documents_docx_list = [os.path.join(DOCUMENTS_DOCX_FOLDER, filename) for filename in os.listdir(DOCUMENTS_DOCX_FOLDER)]

def getText(filename):
    """
    Extract text from a docx file
    """
    doc = docx.Document(filename)
    fullText = []
    for para in doc.paragraphs:
        fullText.append(para.text)
    return '\n'.join(fullText)

def create_textfilename(docx_file_name):
    """
    Generate a filename of the txt file based on the filename of the docx file
    """
    pathlist = list(os.path.split(docx_file_name))
    pathlist[-2] = TEXTFILES_FOLDER
    newpath = os.path.join(*pathlist)
    filename, file_extension = os.path.splitext(newpath)
    newfilenm = filename + '.txt'
    return newfilenm

def read_texts():
    """
    Read the text from all docx files
    Returns a dict with keys = docx filenames and values are texts
    Also stores all texts as .txt
    """
    texts = {}
    for filename in tqdm_notebook(documents_docx_list):
        if '~$' in filename:
            continue
        text = getText(filename)
        textfilenm = create_textfilename(filename)
        filenm_short = os.path.splitext(os.path.split(textfilenm)[-1])[0]
        texts[filenm_short] = text
        
        with open(textfilenm, 'wt') as out:
            out.write(text)
        
    return texts
        
texts = read_texts()        
print(len(texts.keys()))
print(list(texts.items())[:3])

/home/hugo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/1302 [00:00<?, ?it/s]

1302
[('ESMA 2019 93', 'ESMA CONSULTS ON THE COMMERCIAL TERMS FOR PROVIDING CLIENT CLEARING SERVICES UNDER EMIR\n03 October 2019\xa0\nPOST TRADING\nThe European Securities and Markets Authority (ESMA), the EU’s securities markets regulator, has today published a\xa0\xa0(CP) on draft technical advice to the European Commission (EC) on specifying the conditions under which commercial terms are to be considered fair, reasonable, non-discriminatory and transparent (FRANDT) where clearing service providers offer clearing services to clients.\nDuring the implementation of EMIR’s clearing obligation, several counterparties have experienced issues around access to clearing. In response to this access issue EMIR Refit has introduced a number of measures to address it, including the FRANDT requirements.\nThe aim of FRANDT for client clearing services\nThe FRANDT requirements are part of a broader set of regulatory efforts to enhance access to clearing. The proposal on how to specify the conditio

## Combine text and labels

In [20]:
from tqdm import tqdm_notebook

for label_line in tqdm_notebook(labels):
    document_name = label_line["Document"]
    document_id = os.path.splitext(document_name)[0]
    label_line['id'] = document_id
    
    text = texts[document_id]
    label_line['text'] = text

raw_data = {line['id']: line for line in labels}
with open(RAW_DATA_JSON_FILE, 'wt') as out:
    json.dump(raw_data, out)


/home/hugo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  This is separate from the ipykernel package so we can avoid doing imports until


  0%|          | 0/1302 [00:00<?, ?it/s]

## Preprocess Texts

In [21]:
institutions = set()
for key in raw_data.keys():
    institution = key.split(' ')[0].lower()
    institutions.add(institution)
    
print(institutions)
#TODO: add more institutions

{'eige', 'eda', 'ecdc', 'eit', 'ema', 'euipo', 'europol', 'easa', 'eu-lisa', 'eea', 'berec', 'emsa', 'sbr', 'cepol', 'cvpo', 'esma', 'fra', 'eba', 'efca', 'eiopa', 'easo', 'etf', 'cedefop', 'echa', 'acer', 'frontex', 'eurojust', 'era', 'emcdda', 'eurofound', 'efsa', 'cdt', 'eu-osha', 'enisa'}


In [22]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
import re
stopWords = set(stopwords.words('english'))


remove_digits = str.maketrans(' ', ' ', string.digits)
remove_punct = str.maketrans(' ', ' ', string.punctuation)
# remove_stopwords = str.maketrans(' ', ' ', stopWords)



lemmatizer = WordNetLemmatizer()

def process_word(word:str):
    word = word.lower()
    word = lemmatizer.lemmatize(word)
    
    return word

# def remove_word(word):
#     if word in stopWords:
#         return True
#     elif word.startswith('\\u'):
#         return True
#     elif word in "!@#$%*()_+-=?/<,>.":
#         return True
#     return False

def preprocess_text(text):
    text = text.lower()
    text = text.translate(remove_punct)
    text = text.translate(remove_digits)
#     text = text.translate(remove_stopwords)
    text = re.sub(r'\u200b', ' ', text)
    text = re.sub(r'\n', ' ', text)
    wordlist = word_tokenize(text)
    wordlist = [lemmatizer.lemmatize(word) for word in wordlist if not (word in stopWords or word in institutions)]
    
    processed_text = ' '.join(wordlist)
    
    return processed_text
#     input(wordlist)
    


In [23]:
for identifier, data_line in tqdm_notebook(raw_data.items()):
    text = data_line['text']
    processed_text = preprocess_text(text)
    raw_data[identifier]['processed_text']=processed_text
    
print(list(raw_data.items())[0])

/home/hugo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  """Entry point for launching an IPython kernel.


  0%|          | 0/1302 [00:00<?, ?it/s]

('ACER 2019 1', {'Document': 'ACER 2019 1.docx', 'Dimension 1st': '1', 'Dimension 2nd': '1', 'id': 'ACER 2019 1', 'text': "ACER analyses national methodologies for electricity transmission tariffs in the EU\n\n23/12/2019\nThe European Union Agency for the Cooperation of Energy Regulators (ACER) released today a report reviewing the status of methodologies for electricity transmission tariffs in the European Union Member States. \n\nThis report\u200b is a contribution towards the Clean Energy Package objective to increase transparency and comparability in tariff-setting. The report also presents the findings of ACER's monitoring of transmission charges paid by producers. The status review of the distribution tariff structures and the identification of best tariff practices will be subject to future ACER reports. Find below the main findings in different areas.\n\nMethodology setting\n\nIn all but three jurisdictions/countries the corresponding National Regulatory Authority (NRA) directl

In [24]:
import json

with open(PREPROCESSED_JSON_FILE, 'wt') as out:
    json.dump(raw_data, out)
    assert os.path.exists(PREPROCESSED_JSON_FILE), "Json file must be created."

In [25]:
!ls

 agency_counts.csv			 label_agency_heatmap.png
 agency_label_crosstab.csv		 label_counts.csv
 agency_label_crosstab_percentages.csv	 labels2.json
 all_data.json				 labels.csv
 all_data_no_predictions.csv		 labels.json
 analyze.ipynb				 Machine_Learning.ipynb
'Coding for Hugo.xlsx'			 make_new_labels_file.ipynb
 confidence_pivot.csv			 pycaret.ipynb
 confidence_pivot_only_agencies.csv	 raw_data.json
 confidence_pivot_only_labels.csv	 regulatory_vs_non_regulatory.csv
 data_with_labels.csv			 regulatory_vs_non_regulatory.png
 documents_txt				 results
 dpc2vec.ipynb				 SVM_trained.pk
 evaluation_pivot.csv			'Training Set for Hugo'
 evaluation_pivot_only_agencies.csv	 vectorizer.pk
 evaluation_pivot_only_labels.csv	 year_label_heatmap.png
 experiments_results


## Make DTM

In [26]:
import numpy as np
texts = []
y_1 = []
y_2 = []

for identifier, data_line in tqdm_notebook(raw_data.items()):
    texts.append(data_line.get('processed_text'))
    y_1.append(data_line.get("Dimension 1st"))
    y_2.append(data_line.get("Dimension 2nd"))

y_1 = np.array(y_1, dtype = np.int16)
y_2 = np.array(y_2, dtype = np.int16)
texts = np.array(texts)

y1_all = y_1


y_1

/home/hugo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


  0%|          | 0/1302 [00:00<?, ?it/s]

array([1, 1, 2, ..., 3, 1, 2], dtype=int16)

In [27]:
from collections import Counter

In [28]:
count = Counter(y_1)
count

Counter({1: 328, 2: 547, 3: 302, 4: 125})

In [29]:
np.array(list(count.values()))/sum(list(count.values()))

array([0.25192012, 0.42012289, 0.23195084, 0.09600614])

#### Shuffle

In [30]:
# np.random.seed(1)
# random_array = np.random.rand(len(texts))

# indices = np.argsort(random_array)

# texts_ = texts[indices]
# y_1 = y_1[indices]
# y_2 = y_2[indices]
# print(len(texts))

### Separate Train-test

In [31]:
from sklearn.model_selection import train_test_split

texts_train, texts_test, y1_train, y1_test, y2_train, y2_test = train_test_split(texts, y_1, y_2, train_size=0.90, random_state=42)

assert len(texts_train) == len(y1_train) == len(y2_train)
assert len(texts_test) == len(y1_test) == len(y2_test)


In [32]:
y_1

array([1, 1, 2, ..., 3, 1, 2], dtype=int16)

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(sublinear_tf = True)
X_train = vectorizer.fit_transform(texts_train)

print(X_train.shape)

(1171, 14744)


#### Store vectorizer

In [34]:
import pickle

with open('vectorizer.pk', 'wb') as fin:
    pickle.dump(vectorizer, fin)

In [35]:
ls

 agency_counts.csv                       label_agency_heatmap.png
 agency_label_crosstab.csv               label_counts.csv
 agency_label_crosstab_percentages.csv   labels2.json
 all_data.json                           labels.csv
 all_data_no_predictions.csv             labels.json
 analyze.ipynb                           Machine_Learning.ipynb
'Coding for Hugo.xlsx'                   make_new_labels_file.ipynb
 confidence_pivot.csv                    pycaret.ipynb
 confidence_pivot_only_agencies.csv      raw_data.json
 confidence_pivot_only_labels.csv        regulatory_vs_non_regulatory.csv
 data_with_labels.csv                    regulatory_vs_non_regulatory.png
 documents_txt/                          results/
 dpc2vec.ipynb                           SVM_trained.pk
 evaluation_pivot.csv                   'Training Set for Hugo'/
 evaluation_pivot_only_agencies.csv      vectorizer.pk
 evaluation_pivot_only_labels.csv        year_label_heatmap.png
 experiments_results/


## Test different models

Experiments:

* SVM 1st dim and SVM 2nd dim
* randm forest 1st dim and 2nd dim
* logreg 1st and 2nd
* multilabel classification

In [36]:
display_cols_svm = ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_C', 'param_kernel', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score', 'std_train_score']

results_folder = "experiments_results"

In [37]:
if not os.path.exists(results_folder):
    os.makedirs(results_folder)

In [38]:
def make_results_filename(classifier, dim, comment = ""):
    return f"{results_folder}/{classifier}_{dim}_{comment}.csv"

In [39]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

X_test = vectorizer.transform(texts_test)

def evaluate_on_test(X_train, X_test, y_train, y_test, best_params, algorithm):
    print(best_params)
    print("-"*80, end = '\n\n')
    
    final_model = algorithm(**best_params)
    final_model.fit(X= X_train, y = y_train)
    y_pred = final_model.predict(X_test)
    
    print(classification_report(y_test, y_pred))
    print("-"*80,end = '\n\n')
    print(confusion_matrix(y1_test, y_pred))



### SVM

#### Define experiment

In [40]:
import pandas as pd 
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

def svc_experiment(X,y):
    svc = SVC()
    parameters = {'kernel':('linear', 'rbf'), 'C':[10, 100, 1000, 1e4, 1e5, 1e6]} #0.1, 1, 10,

    clf = GridSearchCV(svc, parameters, n_jobs=3, scoring='precision_weighted', cv=10, verbose=10, return_train_score=True)
    clf.fit(X, y)
    
    svm_results = clf.cv_results_
    
    return clf, svm_results


#### 1st dim

In [41]:
svm_y1_cv_model, svm_y1_results_json = svc_experiment(X= X_train, y = y1_train)

svm_y1_results = pd.DataFrame(svm_y1_results_json)

Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   2 tasks      | elapsed:    5.6s
[Parallel(n_jobs=3)]: Done   7 tasks      | elapsed:   14.5s
[Parallel(n_jobs=3)]: Done  12 tasks      | elapsed:   22.3s
[Parallel(n_jobs=3)]: Done  19 tasks      | elapsed:   36.0s
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:   50.1s
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:  1.1min
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:  1.4min
[Parallel(n_jobs=3)]: Done  55 tasks      | elapsed:  1.7min
[Parallel(n_jobs=3)]: Done  66 tasks      | elapsed:  2.1min
[Parallel(n_jobs=3)]: Done  79 tasks      | elapsed:  2.4min
[Parallel(n_jobs=3)]: Done  92 tasks      | elapsed:  2.8min
[Parallel(n_jobs=3)]: Done 107 tasks      | elapsed:  3.2min
[Parallel(n_jobs=3)]: Done 120 out of 120 | elapsed:  3.5min finished


In [42]:
svm_y1_results[display_cols_svm].sort_values(by="mean_test_score", ascending=False)

mean_fit_time  std_fit_time  mean_score_time  std_score_time    param_C  \
0        2.839311      0.272730         0.199871        0.025790         10   
3        3.262792      0.458160         0.208619        0.041545        100   
1        3.499767      0.546018         0.222708        0.056728         10   
5        3.497172      0.472274         0.256351        0.076829       1000   
7        2.842199      0.294361         0.203070        0.028338    10000.0   
9        3.522713      0.479526         0.225861        0.058160   100000.0   
11       2.934482      0.217782         0.203712        0.025514  1000000.0   
2        3.735982      0.784109         0.257373        0.059612        100   
4        2.650310      0.273862         0.180008        0.020459       1000   
6        3.116816      0.685410         0.195604        0.035510    10000.0   
8        2.877185      0.178530         0.198021        0.035355   100000.0   
10       2.692070      0.362948         0.194930        0.033207  1000000.0   

   param_kernel                                params  mean_test_score  \
0        linear         {'C': 10, 'kernel': 'linear'}         0.712857   
3           rbf           {'C': 100, 'kernel': 'rbf'}         0.709670   
1           rbf            {'C': 10, 'kernel': 'rbf'}         0.709237   
5           rbf          {'C': 1000, 'kernel': 'rbf'}         0.708740   
7           rbf       {'C': 10000.0, 'kernel': 'rbf'}         0.708740   
9           rbf      {'C': 100000.0, 'kernel': 'rbf'}         0.708740   
11          rbf     {'C': 1000000.0, 'kernel': 'rbf'}         0.708740   
2        linear        {'C': 100, 'kernel': 'linear'}         0.695526   
4        linear       {'C': 1000, 'kernel': 'linear'}         0.680395   
6        linear    {'C': 10000.0, 'kernel': 'linear'}         0.680395   
8        linear   {'C': 100000.0, 'kernel': 'linear'}         0.680395   
10       linear  {'C': 1000000.0, 'kernel': 'linear'}         0.680395   

    std_test_score  rank_test_score  mean_train_score  std_train_score  
0         0.031661                1          0.994698         0.001213  
3         0.038082                2          0.999337         0.000434  
1         0.031450                3          0.997544         0.000463  
5         0.039833                4          1.000000         0.000000  
7         0.039833                4          1.000000         0.000000  
9         0.039833                4          1.000000         0.000000  
11        0.039833                4          1.000000         0.000000  
2         0.030588                8          0.999243         0.000379  
4         0.019466                9          1.000000         0.000000  
6         0.019466                9          1.000000         0.000000  
8         0.019466                9          1.000000         0.000000  
10        0.019466                9          1.000000         0.000000

In [43]:
outfile = make_results_filename('svm', 1)
print(outfile)

svm_y1_results.to_csv(outfile, sep='\t')

!ls experiments_results

experiments_results/svm_1_.csv
LR_1_.csv  LR_2_.csv  RF_1_.csv  RF_2_.csv  svm_1_.csv	svm_2_.csv


In [44]:
svm_y1_cv_model.best_params_

{'C': 10, 'kernel': 'linear'}

In [45]:


# X_test = vectorizer.transform(texts_test)

# cv_model.best_params_

# final_model = SVC(C = cv_model.best_params_['C'], kernel = cv_model.best_params_['kernel'])
# final_model.fit(X= X_train, y = y1_train)
# y1_pred = final_model.predict(X_test)




In [46]:
# from sklearn.metrics import classification_report
# print(classification_report(y1_test, y1_pred))

In [47]:
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y1_test, y1_pred)

In [48]:
# from sklearn.metrics import classification_report
# from sklearn.metrics import confusion_matrix

# def evaluate_on_test(X_train, X_test, y_train, y_test, best_params):
#     print(best_params)
#     print("-"*80, end = '\n\n')
    
#     final_model = SVC(**best_params)
#     final_model.fit(X= X_train, y = y_train)
#     y_pred = final_model.predict(X_test)
    
#     print(classification_report(y_test, y_pred))
#     print("-"*80,end = '\n\n')
#     print(confusion_matrix(y1_test, y1_pred))



In [49]:
evaluate_on_test(X_train, X_test, y1_train, y1_test, svm_y1_cv_model.best_params_, algorithm=SVC)

{'C': 10, 'kernel': 'linear'}
--------------------------------------------------------------------------------

              precision    recall  f1-score   support

           1       0.78      0.85      0.82        34
           2       0.70      0.81      0.75        52
           3       0.81      0.60      0.69        35
           4       0.62      0.50      0.56        10

    accuracy                           0.74       131
   macro avg       0.73      0.69      0.70       131
weighted avg       0.74      0.74      0.74       131

--------------------------------------------------------------------------------

[[29  3  1  1]
 [ 5 42  4  1]
 [ 2 11 21  1]
 [ 1  4  0  5]]


### Train and store the svm 

In [50]:
X_all = vectorizer.transform(texts)
X_all.shape

(1302, 14744)

In [51]:
y1_all.shape

(1302,)

In [52]:
from sklearn.svm import SVC

svc = SVC(probability=True, **svm_y1_cv_model.best_params_)
svc.fit(X_all, y1_all)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [53]:
import pickle
with open("SVM_trained.pk", "wb") as out:
    pickle.dump(svc, out)

In [54]:
ls

 agency_counts.csv                       label_agency_heatmap.png
 agency_label_crosstab.csv               label_counts.csv
 agency_label_crosstab_percentages.csv   labels2.json
 all_data.json                           labels.csv
 all_data_no_predictions.csv             labels.json
 analyze.ipynb                           Machine_Learning.ipynb
'Coding for Hugo.xlsx'                   make_new_labels_file.ipynb
 confidence_pivot.csv                    pycaret.ipynb
 confidence_pivot_only_agencies.csv      raw_data.json
 confidence_pivot_only_labels.csv        regulatory_vs_non_regulatory.csv
 data_with_labels.csv                    regulatory_vs_non_regulatory.png
 documents_txt/                          results/
 dpc2vec.ipynb                           SVM_trained.pk
 evaluation_pivot.csv                   'Training Set for Hugo'/
 evaluation_pivot_only_agencies.csv      vectorizer.pk
 evaluation_pivot_only_labels.csv        year_label_heatmap.png
 experiments_results/


#### 2nd dim

In [55]:
svm_y2_cv_model, svm_y2_results_json = svc_experiment(X_train, y2_train)
svm_y2_results = pd.DataFrame(svm_y2_results_json)


Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   2 tasks      | elapsed:    6.2s
[Parallel(n_jobs=3)]: Done   7 tasks      | elapsed:   14.4s
[Parallel(n_jobs=3)]: Done  12 tasks      | elapsed:   22.1s
[Parallel(n_jobs=3)]: Done  19 tasks      | elapsed:   34.2s
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:   43.5s
[Parallel(n_jobs=3)]: Done  35 tasks      | elapsed:   58.4s
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:  1.2min
[Parallel(n_jobs=3)]: Done  55 tasks      | elapsed:  1.5min
[Parallel(n_jobs=3)]: Done  66 tasks      | elapsed:  1.8min
[Parallel(n_jobs=3)]: Done  79 tasks      | elapsed:  2.1min
[Parallel(n_jobs=3)]: Done  92 tasks      | elapsed:  2.4min
[Parallel(n_jobs=3)]: Done 107 tasks      | elapsed:  2.8min
[Parallel(n_jobs=3)]: Done 120 out of 120 | elapsed:  3.2min finished


In [56]:
svm_y2_results[display_cols_svm]

mean_fit_time  std_fit_time  mean_score_time  std_score_time    param_C  \
0        3.172088      0.553313         0.234160        0.064028         10   
1        2.817281      0.244723         0.192199        0.028273         10   
2        2.757764      0.275318         0.189058        0.031316        100   
3        2.817969      0.381386         0.197623        0.029578        100   
4        2.876647      0.296298         0.202788        0.065638       1000   
5        2.845318      0.276846         0.198888        0.033195       1000   
6        2.626746      0.331761         0.188646        0.020888    10000.0   
7        2.786863      0.356504         0.193177        0.031858    10000.0   
8        2.738735      0.335278         0.185713        0.018529   100000.0   
9        2.765023      0.324701         0.200275        0.037087   100000.0   
10       2.697953      0.259339         0.187313        0.022340  1000000.0   
11       2.800266      0.329143         0.199119        0.026003  1000000.0   

   param_kernel                                params  mean_test_score  \
0        linear         {'C': 10, 'kernel': 'linear'}         0.462075   
1           rbf            {'C': 10, 'kernel': 'rbf'}         0.491324   
2        linear        {'C': 100, 'kernel': 'linear'}         0.456692   
3           rbf           {'C': 100, 'kernel': 'rbf'}         0.481956   
4        linear       {'C': 1000, 'kernel': 'linear'}         0.447109   
5           rbf          {'C': 1000, 'kernel': 'rbf'}         0.481255   
6        linear    {'C': 10000.0, 'kernel': 'linear'}         0.447109   
7           rbf       {'C': 10000.0, 'kernel': 'rbf'}         0.481255   
8        linear   {'C': 100000.0, 'kernel': 'linear'}         0.447109   
9           rbf      {'C': 100000.0, 'kernel': 'rbf'}         0.481255   
10       linear  {'C': 1000000.0, 'kernel': 'linear'}         0.447109   
11          rbf     {'C': 1000000.0, 'kernel': 'rbf'}         0.481255   

    std_test_score  rank_test_score  mean_train_score  std_train_score  
0         0.032599                7          0.990263         0.001338  
1         0.042698                1          0.996025         0.001018  
2         0.031812                8          0.997916         0.000569  
3         0.044471                2          0.999243         0.000378  
4         0.034886                9          1.000000         0.000000  
5         0.042433                3          1.000000         0.000000  
6         0.034886                9          1.000000         0.000000  
7         0.042433                3          1.000000         0.000000  
8         0.034886                9          1.000000         0.000000  
9         0.042433                3          1.000000         0.000000  
10        0.034886                9          1.000000         0.000000  
11        0.042433                3          1.000000         0.000000

In [57]:
outfile = make_results_filename('svm', 2)
print(outfile)

svm_y2_results.to_csv(outfile, sep='\t')

!ls experiments_results

experiments_results/svm_2_.csv
LR_1_.csv  LR_2_.csv  RF_1_.csv  RF_2_.csv  svm_1_.csv	svm_2_.csv


In [58]:
evaluate_on_test(X_train, X_test, y2_train, y2_test, svm_y2_cv_model.best_params_, algorithm=SVC)

{'C': 10, 'kernel': 'rbf'}
--------------------------------------------------------------------------------

              precision    recall  f1-score   support

           1       0.50      0.50      0.50        28
           2       0.42      0.57      0.48        44
           3       0.64      0.64      0.64        42
           4       0.00      0.00      0.00        17

    accuracy                           0.50       131
   macro avg       0.39      0.43      0.41       131
weighted avg       0.45      0.50      0.47       131

--------------------------------------------------------------------------------

[[22  8  4  0]
 [ 2 32 18  0]
 [ 3 12 20  0]
 [ 1  8  0  1]]


### Random Forest

In [59]:
display_cols_RF = ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_n_estimators', 'param_max_depth', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score', 'std_train_score']


#### Define Experiment

In [60]:
from sklearn.ensemble import RandomForestClassifier

def RF_experiment(X,y):
    rf = RandomForestClassifier()
    parameters = {'n_estimators':[10,20,50, 100, 120, 150, 200, 250, 300, 1000], 'max_depth': [10, 20, 50, None]}

    clf = GridSearchCV(rf, parameters, n_jobs=3, scoring='f1_weighted', cv=10, verbose=10, return_train_score=True)
    clf.fit(X, y)
    
    svm_results = pd.DataFrame(clf.cv_results_)
    
    return clf, svm_results

#### 1st dim

In [61]:
RF_y1_cv_model, RF_y1_results = RF_experiment(X_train, y1_train)

Fitting 10 folds for each of 40 candidates, totalling 400 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Batch computation too fast (0.1099s.) Setting batch_size=2.
[Parallel(n_jobs=3)]: Done   2 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done   8 tasks      | elapsed:    0.4s
[Parallel(n_jobs=3)]: Done  18 tasks      | elapsed:    1.0s
[Parallel(n_jobs=3)]: Done  32 tasks      | elapsed:    3.2s
[Parallel(n_jobs=3)]: Batch computation too slow (2.2564s.) Setting batch_size=1.
[Parallel(n_jobs=3)]: Done  46 tasks      | elapsed:    6.6s
[Parallel(n_jobs=3)]: Done  59 tasks      | elapsed:   10.8s
[Parallel(n_jobs=3)]: Done  68 tasks      | elapsed:   15.8s
[Parallel(n_jobs=3)]: Done  79 tasks      | elapsed:   21.0s
[Parallel(n_jobs=3)]: Done  90 tasks      | elapsed:   29.0s
[Parallel(n_jobs=3)]: Done 103 tasks      | elapsed:   50.7s
[Parallel(n_jobs=3)]: Done 116 tasks      | elapsed:   52.1s
[Parallel(n_jobs=3)]: Done 131 tasks      | elapsed:   54.8s
[Parallel(n_jobs=3)]: Done 14

KeyboardInterrupt: 

In [ ]:
RF_y1_results[display_cols_RF]

In [ ]:
outfile = make_results_filename('RF', 1)
print(outfile)

RF_y1_results.to_csv(outfile, sep='\t')

!ls experiments_results

In [ ]:
RF_y1_cv_model.best_params_

In [ ]:
evaluate_on_test(X_train, X_test, y1_train, y1_test, RF_y1_cv_model.best_params_, algorithm=RandomForestClassifier)

In [ ]:
# RF_y1_cv_model.best_params_

In [ ]:

# X_test = vectorizer.transform(texts_test)

# RF_y1_cv_model.best_params_

# RF_y1_final_model = RandomForestClassifier(
#     max_depth = RF_y1_cv_model.best_params_['max_depth'], 
#     n_estimators = RF_y1_cv_model.best_params_['n_estimators'])

# RF_y1_final_model.fit(X= X_train, y = y1_train)
# RF_y1_pred = RF_y1_final_model.predict(X_test)


In [ ]:
# from sklearn.metrics import classification_report
# print(classification_report(y1_test, RF_y1_pred))

In [ ]:
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y1_test, RF_y1_pred)

#### 2nd dim

In [ ]:
RF_y2_cv_model, RF_y2_results = RF_experiment(X_train, y2_train)

In [ ]:
RF_y2_results[display_cols_RF]

In [ ]:
outfile = make_results_filename('RF', 2)
print(outfile)

RF_y2_results.to_csv(outfile, sep='\t')

!ls experiments_results

In [ ]:
RF_y1_cv_model.best_params_

In [ ]:
evaluate_on_test(
    X_train, 
    X_test, 
    y2_train, 
    y2_test, 
    RF_y2_cv_model.best_params_,
    algorithm= RandomForestClassifier)

In [ ]:

# X_test = vectorizer.transform(texts_test)

# RF_y2_cv_model.best_params_

# RF_y2_final_model = RandomForestClassifier(
#     max_depth = RF_y2_cv_model.best_params_['max_depth'], 
#     n_estimators = RF_y2_cv_model.best_params_['n_estimators'])

# RF_y2_final_model.fit(X= X_train, y = y2_train)
# RF_y2_pred = RF_y2_final_model.predict(X_test)


In [ ]:
# from sklearn.metrics import classification_report
# print(classification_report(y2_test, RF_y2_pred))

In [ ]:
# from sklearn.metrics import confusion_matrix
# confusion_matrix(y2_test, RF_y2_pred)

### Logistic Regression

In [ ]:
display_cols_LR = ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_penalty', 'param_C', 'params', 'mean_test_score', 'std_test_score', 'rank_test_score', 'mean_train_score', 'std_train_score']


#### Define Experiment

In [ ]:
from sklearn.linear_model import LogisticRegression

def RF_experiment(X,y):
    lr = LogisticRegression()
    parameters = {'penalty':['l1', 'l2'], 'C':[0.1, 1, 10, 20, 100, 200, 1000, 2000, 1e4, 1e5]}

    clf = GridSearchCV(lr, parameters, n_jobs=3, scoring='f1_weighted', cv=10, verbose=10, return_train_score=True)
    clf.fit(X, y)
    
    svm_results = pd.DataFrame(clf.cv_results_)
    
    return clf, svm_results

#### 1st dim

In [ ]:
LR_y1_cv_model, LR_y1_results = RF_experiment(X_train, y1_train)

In [ ]:
LR_y1_results[display_cols_LR]

In [ ]:
outfile = make_results_filename('LR', 1)
print(outfile)

LR_y1_results.to_csv(outfile, sep='\t')

!ls experiments_results

In [ ]:
evaluate_on_test(
    X_train, 
    X_test, 
    y1_train, 
    y1_test, 
    LR_y1_cv_model.best_params_,
    algorithm= LogisticRegression)

In [ ]:


# X_test = vectorizer.transform(texts_test)

# LR_cv_model.best_params_

# final_model = LR(C = cv_model.best_params_['C'], kernel = cv_model.best_params_['kernel'])
# final_model.fit(X= X_train, y = y1_train)
# y1_pred = final_model.predict(X_test)



#### 2nd dim

In [ ]:
LR_y2_cv_model, LR_y2_results = RF_experiment(X_train, y2_train)

In [ ]:
LR_y2_results[display_cols_LR]

In [ ]:
outfile = make_results_filename('LR', 2)
print(outfile)

LR_y1_results.to_csv(outfile, sep='\t')

!ls experiments_results

In [ ]:
evaluate_on_test(
    X_train, 
    X_test, 
    y2_train, 
    y2_test, 
    LR_y2_cv_model.best_params_,
    algorithm= LogisticRegression)

## Label analysis

In this section I will explore how often a model trained on the first demention predicts a label from the second demention. But first I will explore if labels "correlate".

In [ ]:
y_1

In [ ]:
y_2

In [ ]:
from collections import Counter

In [ ]:
Counter(y_1)

In [ ]:
Counter(y_2)

In [ ]:
conf_matrix = np.zeros((4,4), dtype = np.int16)
conf_matrix

In [ ]:
for first, second in zip(y_1, y_2):
    conf_matrix[first-1, second-1] += 1
    
conf_matrix

In [ ]:
from collections import defaultdict

d = defaultdict(lambda :0)

for first, second in zip(y_1, y_2):
    d[f"{first}_{second}"] += 1


sorted(d.items(), key=lambda x:x[0])

### Analyze different classifiers

First write the evaluation function

In [ ]:
from collections import defaultdict


def evaluate_together(y_1_true, y_2_true, y_1_pred):
    assert len(y_1_true) == len(y_2_true) == len(y_1_pred)
#     results = defaultdict(lambda :defaultdict(lambda : ))
    results = {
        "first_degree": 0,
        "second_degree": 0,
        "false": 0
    }
    total = 0
    for true_1, true_2, pred in zip(y_1_true, y_2_true, y_1_pred):
        if pred == true_1:
            results["first_degree"] += 1
        elif pred == true_2:
            results["second_degree"] += 1
        else:
            results["false"] += 1
            
        total += 1
        
    assert total == len(y_1_true) == len(y_2_true) == len(y_1_pred) == total
    
    return results, total
    
def return_defdict():
    return defaultdict(int)
    
def evaluate_together2(y_1_true, y_2_true, y_1_pred):
    assert len(y_1_true) == len(y_2_true) == len(y_1_pred)
    results = defaultdict(return_defdict)
#     results = {
#         "first_degree": 0,
#         "second_degree": 0,
#         "false": 0
#     }
    total = 0
    for true_1, true_2, pred in zip(y_1_true, y_2_true, y_1_pred):
        if pred == true_1:
            results[true_1]["first_degree"] += 1
        elif pred == true_2:
            results[true_1]["second_degree"] += 1
        else:
            results[true_1]["false"] += 1
            
        total += 1
        
    assert total == len(y_1_true) == len(y_2_true) == len(y_1_pred) == total
    
    return results, total
        

#### SVM

In [ ]:
Counter(y1_test)

In [ ]:
svc = SVC(**svm_y1_cv_model.best_params_)
svc.fit(X_train, y1_train)

y_pred = svc.predict(X_test)

results, total = evaluate_together(y1_test, y2_test, y_pred)
print(results)
print('2nd degree accuracy:\t', (results['first_degree'] + results['second_degree'])/total)

In [ ]:

results2, total2 = evaluate_together2(y1_test, y2_test, y_pred)
results2

In [ ]:
for label, res in sorted(results2.items(), key= lambda x:x[0]):
    fd = res.get('first_degree',0)
    sd = res.get('second_degree', 0)
    errors = res.get('false',0)
    
#     print(fd,sd,errors)
    first_degree_precision = fd / (fd+sd+errors)
    second_degree_precision = (fd + sd)/ (fd + sd + errors)
    print("-",label)
    print('\tfirst degree:\t', first_degree_precision)
    print('\tsecond degree:\t', second_degree_precision)
#     print(label, res)

#### RF

In [ ]:
rf = RandomForestClassifier(**RF_y1_cv_model.best_params_)
rf.fit(X_train, y1_train)

y_pred = rf.predict(X_test)

results, total = evaluate_together(y1_test, y2_test, y_pred)
print(results)
print('2md degree accuracy:\t', (results['first_degree'] + results['second_degree'])/total)

print('-'*50)

results2, total2 = evaluate_together2(y1_test, y2_test, y_pred)
print(results2)

## SMOTE

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

X_test = vectorizer.transform(texts_test)

def evaluate_on_test_SMOTE(X_train, X_test, y_train, y_test, best_params, algorithm):
    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(X_train, y_train)
    print(best_params)
    print("-"*80, end = '\n\n')
    
    final_model = algorithm(**best_params)
    final_model.fit(X= X_res, y = y_res)
    y_pred = final_model.predict(X_test)
    
    print(classification_report(y_test, y_pred))
    print("-"*80,end = '\n\n')
    print(confusion_matrix(y1_test, y_pred))
    
    

In [ ]:



# grid = GridSearchCV(model, params, ...)
# grid.fit(X, y)

In [ ]:
import pandas as pd 
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE 
from imblearn.pipeline import Pipeline


def svc_SMOTE_experiment(X,y):
        
    sm = SMOTE(random_state=42)
    X_res, y_res = sm.fit_resample(X, y)
    
    model = Pipeline([
        ('sampling', SMOTE()),
        ('classification', SVC())
    ])
    

    parameters = {'classification__kernel':('linear', 'rbf'), 'classification__C':[100, 1000, 1e4, 1e5, 1e6]} #0.1, 1, 10,
    
    clf = GridSearchCV(model, parameters, n_jobs=3, scoring='f1_weighted', cv=10, verbose=10, return_train_score=True)
    clf.fit(X_res, y_res)
    
    svm_results = clf.cv_results_
    
    return clf, svm_results


In [ ]:
svm_y1_cv_model, svm_y1_results_json = svc_SMOTE_experiment(X= X_train, y = y1_train)

svm_y1_results = pd.DataFrame(svm_y1_results_json)

In [ ]:
outfile = make_results_filename('svm', 1)
print(outfile)

svm_y1_results.to_csv(outfile, sep='\t')

In [ ]:
svm_y1_results

In [ ]:
evaluate_on_test_SMOTE(X_train, X_test, y1_train, y1_test, svm_y1_cv_model.best_params_, algorithm=SVC)

## Doc2Vec



In [ ]:
import pandas as pd
import numpy as np
from tqdm import tqdm
tqdm.pandas(desc="progress-bar")
from gensim.models import Doc2Vec
from sklearn import utils
from sklearn.model_selection import train_test_split
import gensim
from sklearn.linear_model import LogisticRegression
from gensim.models.doc2vec import TaggedDocument
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
train_tagged = [TaggedDocument(text,[label]) for text, label in zip(texts_train, y1_train)]
# train.apply(
#     lambda r: TaggedDocument(words=tokenize_text(r['narrative']), tags=[r.Product]), axis=1)
test_tagged = [TaggedDocument(text,[label]) for text, label in zip(texts_test, y1_test)]
#                 test.apply(
#     lambda r: TaggedDocument(words=tokenize_text(r['narrative']), tags=[r.Product]), axis=1)

In [ ]:
import multiprocessing

cores = multiprocessing.cpu_count() -1

In [ ]:
model_dbow = Doc2Vec(dm=0, vector_size=100, negative=5, hs=0, min_count=2, sample = 0, workers=cores)


In [ ]:
model_dbow.build_vocab([x for x in tqdm_notebook(train_tagged)])

In [ ]:
for epoch in range(30):
    model_dbow.train(utils.shuffle([x for x in tqdm(train_tagged)]), total_examples=len(train_tagged), epochs=1)
    model_dbow.alpha -= 0.002
    model_dbow.min_alpha = model_dbow.alpha

## Multilabel Classification

